
services:
  backend:
    container_name: backend_music
    restart: always
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /videos:/app/downloads/videos  # Persistir downloads
      - /musicas:/app/downloads/musicas  # Persistir downloads
      - ./main.py:/app/main.py       # Montar main.py no container
      - ./filmes:/app/downloads/filmes #para tentar ver os filmes no jellyfinn
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
    # Healthcheck opcional para monitoramento
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/api/health"]
      interval: 15s
      timeout: 5s
      retries: 3
